### ISSUE TITLE
Pruebas Travis

### ISSUE THREAD

**Issue by PedroRamosRguez** [ULL-ESIT-GRADOII-DSI/karma-y-travis-rafa-pedro-dani_2#1]
@Rafaherrero @DanielRamosAcosta .  Las pruebas en Travis funcionan como si se realizaran en consola por Karma. El commit  862f3a8 y el commit b770cbd arreglaron  todos los problemas.

**Comment by DanielRamosAcosta** [comment]
@alu0100505078 Pedro mira a ver si puedes poner la insignia en el [README.md](https://github.com/ULL-ESIT-GRADOII-DSI/karma-y-travis-rafa-pedro-dani_2/blob/dev/README.md)

**Comment by PedroRamosRguez** [comment]
@DanielRamosAcosta  Completado.
